name: PR Build

on:
  pull_request:
    # run on every PR

concurrency:
  group: pr-build-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

      - name: Set up Python
        if: steps.changes.outputs.backend == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build backend
        if: steps.changes.outputs.backend == 'true'
        run: |
          cd backend
          pip install -r requirements.txt
          python -m py_compile $(git ls-files '*.py')

      - name: Set up Node
        if: steps.changes.outputs.frontend == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Build frontend
        if: steps.changes.outputs.frontend == 'true'
        run: |
          cd frontend
          npm ci
          npm run build
